---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  labels:
    argocd.argoproj.io/type: AoA
  namespace: argocd
  annotations:
      notifications.argoproj.io/subscribe.on-deployed.discord: "alert"
      notifications.argoproj.io/subscribe.on-sync-failed.discord: "alert"
      notifications.argoproj.io/subscribe.on-sync-running.discord: "alert"
      notifications.argoproj.io/subscribe.on-sync-succeeded.discord: "alert"
spec:
  project: default
  sources:
    - repoURL: https://github.com/gitops-ziichat/argo-config.git
      targetRevision: HEAD
      path: app-of-apps/apps/auto-discovery
    - repoURL: https://github.com/gitops-ziichat/argo-config.git
      targetRevision: HEAD
      path: app-of-apps/apps/commands
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
