---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  labels:
    argocd.argoproj.io/type: AoA
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.app-sync-running.discord: alerts
    notifications.argoproj.io/subscribe.app-sync-failed.discord: alerts
    notifications.argoproj.io/subscribe.sync-operation-change.discord: alerts
spec:
  project: default
  sources:
    - repoURL: https://github.com/gitops-ziichat/argo-config.git
      targetRevision: HEAD
      path: app-of-apps/addons
    - repoURL: https://github.com/gitops-ziichat/argo-config.git
      targetRevision: HEAD
      path: app-of-apps/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
