---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-pull-requests
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - scmProvider:
                    github:
                      organization: gitops-ci-cd
                      tokenRef:
                        secretName: github-token
                        key: token
                    filters:
                      - repositoryMatch: '.+-deployment$'
                        pathsExist:
                          - overlays/ephemeral/kustomization.yaml
                - pullRequest:
                    github:
                      owner: gitops-ci-cd
                      repo: '{{ regexReplaceAll "-deployment$" .repository "" }}'
                      tokenRef:
                        secretName: github-token
                        key: token
                      labels:
                        - ephemeral
                    requeueAfterSeconds: 1800 # TODO: Configure webhook to trigger this
          - clusters:
              selector:
                matchLabels:
                  kubernetes.io/environment: sandbox
  template:
    metadata:
      name: '{{ regexReplaceAll "-deployment$" .repository "" }}-{{ .name }}-PR{{ .number }}'
      labels:
        argocd.argoproj.io/chart: 'false'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: apps
      source:
        repoURL: 'https://github.com/{{ .organization }}/{{ .repository }}'
        targetRevision: HEAD
        path: 'overlays/ephemeral'
      destination:
        name: '{{ .name }}'
        namespace: '{{ regexReplaceAll "-deployment$" .repository "" }}-{{ index .metadata.labels "kubernetes.io/environment" }}'
      info:
        - name: 'Pull Request'
          value: 'https://github.com/{{ .organization }}/{{ regexReplaceAll "-deployment$" .repository "" }}/pull/{{ .number }}'
        - name: 'Environment Manifests'
          value: 'https://github.com/{{ .organization }}/{{ .repository }}/tree/{{ .branch }}/overlays/ephemeral'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels: {}
          annotations: {}
        syncOptions:
          - CreateNamespace=true
