---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-pull-requests
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - scmProvider:
                    github:
                      organization: gitops-ci-cd
                      tokenRef:
                        secretName: github-token
                        key: token
                    filters:
                      - repositoryMatch: '.+-deployment$'
                        pathsExist:
                          - overlays/preview/kustomization.yaml
                - pullRequest:
                    github:
                      owner: '{{ .organization }}'
                      repo: '{{ regexReplaceAll "-deployment$" .repository "" }}'
                      tokenRef:
                        secretName: github-token
                        key: token
                      labels:
                        - preview
                    requeueAfterSeconds: 1800 # TODO: Configure webhook to trigger this
          - clusters:
              selector:
                matchLabels:
                  kubernetes.io/environment: sandbox
  template:
    metadata:
      name: '{{ regexReplaceAll "-deployment$" .repository "" }}-{{ .name }}-pr{{ .number }}'
      labels:
        argocd.argoproj.io/type: directory
      annotations:
        github.com/owner: '{{ .organization }}'
        github.com/repo: '{{ regexReplaceAll "-deployment$" .repository "" }}'
        github.com/environment: preview
        github.com/pr: '{{ .number }}'
        github.com/branch: '{{ .branch }}'
        github.com/branch-slug: '{{ .branch_slug }}'
        github.com/ref: '{{ .head_sha }}'
        github.com/author: '{{ .author }}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: apps
      source:
        repoURL: 'https://github.com/{{ .organization }}/{{ .repository }}'
        targetRevision: HEAD
        path: 'overlays/preview'
        kustomize:
          nameSuffix: '-pr{{ .number }}'
          images:
            - 'ghcr.io/{{ .organization }}/{{ regexReplaceAll "-deployment$" .repository "" }}:{{ .head_sha }}'
      destination:
        name: '{{ .name }}'
        namespace: '{{ regexReplaceAll "-deployment$" .repository "" }}-{{ index .metadata.labels "kubernetes.io/environment" }}'
      info:
        - name: 'Pull Request'
          value: 'https://github.com/{{ .organization }}/{{ regexReplaceAll "-deployment$" .repository "" }}/pull/{{ .number }}'
        - name: 'Environment Manifests'
          value: 'https://github.com/{{ .organization }}/{{ .repository }}/tree/{{ .branch }}/overlays/preview'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels: {}
          annotations: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
