---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - scmProvider:
                    github:
                      organization: gitops-ci-cd
                      tokenRef:
                        secretName: github-token
                        key: token
                    filters:
                      - repositoryMatch: -addon$
                        pathsExist:
                          - chart.yaml
                - git:
                  repoURL: '{{ .url }}'
                  revision: HEAD
                  files:
                    - path: chart.yaml
          - clusters:
              selector:
                matchLabels:
                  kubernetes.io/environment: '{{.path.basename}}'

  template:
    metadata:
      name: '{{.repository}}-{{.name}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: addons
      sources:
        - chart: '{{ .chart }}'
          targetRevision: '{{ .targetRevision }}'
          repoURL: '{{ .repoURL }}'
          helm:
            valueFiles:
              - '$values/{{ .metadata.labels["kubernetes.io/environment"] }}/values.yaml'
        - repoURL: '{{ .url }}'
          targetRevision: HEAD
          ref: values
      destination:
        name: '{{.name}}'
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels: {}
          annotations: {}
        syncOptions:
          - CreateNamespace=true
