---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  labels:
    argocd.argoproj.io/type: AoA
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/gitops-ci-cd/argo-config.git
      targetRevision: HEAD
      path: config/config-maps
    - repoURL: https://github.com/gitops-ci-cd/argo-config.git
      targetRevision: HEAD
      path: config/app-projects
    - repoURL: https://github.com/gitops-ci-cd/argo-config.git
      targetRevision: HEAD
      path: config/repositories
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
