---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  kustomize.buildOptions: "--enable-helm"
  resource.customizations: |
    apiextensions.crossplane.io/CompositeResourceDefinition:
      ignoreDifferences: |
        jsonPointers:
          - /spec/versions/*/defaultCompositionRef
