---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  kustomize.buildOptions: "--enable-helm"
  resource.customizations.ignoreDifferences.apiextensions.crossplane.io_CompositeResourceDefinition: |
    jqPathExpressions:
      - '.spec.versions[]?.defaultCompositionRef'
