---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: node-feature-discovery
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/gitops-ci-cd/argo-config
        revision: HEAD
        files:
          - path: app-of-apps/clusters.yaml
    - git:
        repoURL: https://github.com/gitops-ci-cd/addons
        revision: '{{clusters.targetRevision}}'
        files:
          - path: node-feature-discovery/addon.yaml
  template:
    metadata:
      name: 'node-feature-discovery-{{clusters.name}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: addons
      sources:
        - chart: node-feature-discovery
          targetRevision: '{{node-feature-discovery.targetRevision}}'
          repoURL: https://kubernetes-sigs.github.io/node-feature-discovery/charts/
          helm:
            valueFiles:
              - '$values/node-feature-discovery/values.yaml'
        - repoURL: https://github.com/gitops-ci-cd/addons
          targetRevision: '{{clusters.targetRevision}}'
          ref: values
      destination:
        name: '{{clusters.name}}'
        namespace: node-feature-discovery
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels: {}
          annotations: {}
        syncOptions:
          - CreateNamespace=true
