---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-auto-discovery
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - scmProvider:
                    github:
                      organization: gitops-ci-cd
                      tokenRef:
                        secretName: github-token
                        key: token
                    filters:
                      - repositoryMatch: '.+-addon$'
                        pathsExist:
                          - base/kustomization.yaml
                - git:
                    repoURL: 'https://github.com/{{ .organization }}/{{ .repository }}.git'
                    revision: HEAD
                    files:
                      - path: 'overlays/**/kustomization.yaml'
          - clusters:
              selector:
                matchLabels:
                  kubernetes.io/environment: '{{ .path.basename }}'
  template:
    metadata:
      name: '{{ regexReplaceAll "-addon$" .repository "" }}-{{ .name }}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: apps
      source:
        repoURL: 'https://github.com/{{ .organization }}/{{ .repository }}'
        targetRevision: HEAD
        path: 'overlays/{{ index .metadata.labels "kubernetes.io/environment" }}'
      destination:
        name: '{{ .name }}'
      info:
        - name: 'App Repository'
          value: 'https://github.com/{{ .organization }}/{{ regexReplaceAll "-addon$" .repository "" }}'
        - name: 'Environment Manifests'
          value: 'https://github.com/{{ .organization }}/{{ .repository }}/tree/{{ .branch }}/overlays/{{ index .metadata.labels "kubernetes.io/environment" }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
