---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-crossplane
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'crossplane-addon-chart-{{ .name }}'
      labels:
        argocd.argoproj.io/type: helm
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: addons
      sources:
        - chart: crossplane
          targetRevision: 1.18.1
          repoURL: https://charts.crossplane.io/stable
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - '$values/app-of-apps/addons/helm-charts/crossplane/values.yaml'
              - '$values/app-of-apps/addons/helm-charts/crossplane/{{ index .metadata.labels "kubernetes.io/environment" }}.values.yaml'
            valuesObject: {}
        - repoURL: https://github.com/gitops-ci-cd/argo-config
          targetRevision: HEAD
          ref: values
      destination:
        name: '{{ .name }}'
        namespace: crossplane-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels: {}
          annotations: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
