---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-kyverno
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'kyverno-chart-{{.name}}'
      labels:
        argocd.argoproj.io/type: helm
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: addons
      sources:
        - chart: kyverno
          targetRevision: 3.3.3
          repoURL: https://kyverno.github.io/kyverno/
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - '$values/app-of-apps/addons/helm-charts/kyverno/values.yaml'
              - '$values/app-of-apps/addons/helm-charts/kyverno/{{ index .metadata.labels "kubernetes.io/environment" }}.values.yaml'
            valuesObject: {}
        - repoURL: https://github.com/gitops-ci-cd/argo-config
          targetRevision: HEAD
          ref: values
      destination:
        name: '{{.name}}'
        namespace: kyverno
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels: {}
          annotations: {}
        syncOptions:
          - CreateNamespace=true
