---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-node-feature-discovery
  namespace: argocd
  labels:
    argocd.argoproj.io/chart: 'true'
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'node-feature-discovery-{{.name}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: addons
      sources:
        - chart: node-feature-discovery
          targetRevision: 0.15.4
          repoURL: https://kubernetes-sigs.github.io/node-feature-discovery/charts
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - '$values/app-of-apps/addons/helm-charts/node-feature-discovery/global.values.yaml'
              - '$values/app-of-apps/addons/helm-charts/node-feature-discovery/{{ index .metadata.labels "kubernetes.io/environment" }}.values.yaml'
            valuesObject: {}
        - repoURL: https://github.com/gitops-ci-cd/argo-config
          targetRevision: HEAD
          ref: values
      destination:
        name: '{{.name}}'
        namespace: node-feature-discovery
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels: {}
          annotations: {}
        syncOptions:
          - CreateNamespace=true
