---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-traefik
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'traefik-addon-chart-{{ .name }}'
      labels:
        argocd.argoproj.io/type: helm
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: addons
      sources:
        - chart: traefik
          targetRevision: 33.1.0
          repoURL: https://traefik.github.io/charts
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - '$values/app-of-apps/addons/helm-charts/traefik/values.yaml'
              - '$values/app-of-apps/addons/helm-charts/traefik/{{ index .metadata.labels "kubernetes.io/environment" }}.values.yaml'
            valuesObject: {}
        - repoURL: https://github.com/gitops-ci-cd/argo-config
          targetRevision: HEAD
          ref: values
      destination:
        name: '{{ .name }}'
        namespace: traefik
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels: {}
          annotations: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
