---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
data:
  log.level: info
  registries.conf: |
    registries:
      - name: GHCR
        prefix: ghcr.io
        api_url: https://ghcr.io
        default: true
        credentials: pullsecret:argocd/github-registry
  git.commit-message-template: |
    build: automatic update of {{ .AppName }}

    {{ range .AppChanges -}}
    updates image {{ .Image }} tag '{{ .OldTag }}' to '{{ .NewTag }}'
    {{ end -}}
