---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
data:
  registries.conf: |
    registries:
      - name: GHCR
        prefix: ghcr.io
        api_url: https://ghcr.io
        default: true
        credentials: pullsecret:argocd/github-registry

  config.yaml: |
    git:
      write_back_method: git
      default_branch: main
      git_provider: github
      github:
        tokenSecret:
          name: github-token
          key: token
