---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

patches:
  - path: ./config-maps/argocd-cmd-params-cm.yaml
  - path: ./config-maps/argocd-cm.yaml
  - path: ./config-maps/argocd-image-updater-config.yaml
  - path: ./config-maps/argocd-notifications-cm.yaml
